### PR TITLE
Initial menubar feature, changed content view to settings pane

### PR DESCRIPTION
**Pull request by relalis**
Initial implementation of feature requested by #9, could use some cleaning up

### CODE REVIEW

**Comment by mxrlkn** [comment]
If you activate mouselock always, you can't reach the menubar and disable it, which locks your mouse permanently. When it's running as a window app you can always cmd+tab and cmd+q to stop it.

I'm not really sure that I like it as a menubar app. I don't know if that issue can be solved in a proper way.

**Comment by relalis** [comment]
you suggested in the issue to disable the "Always" lock when it's in menubar mode; I think that would be a clean workaround for now. A global hotkey combo to completely disable mouselock is also an idea, I'll put it on the backlog and test it out when I have some free time

**Comment by ghost** [comment]
@relalis can you fork this and implement your PR and release it?

i only use this for LoL so the whole locking issue doesn't apply to me

**Comment by relalis** [comment]
> @relalis can you fork this and implement your PR and release it?
> 
> i only use this for LoL so the whole locking issue doesn't apply to me

I already have a [fork](https://github.com/relalis/mouselock) that this PR is based on, you're welcome to build and run it. A release is available [here](https://github.com/relalis/mouselock/releases/tag/v0.0.6).

Apple decided to deprecate Settings in favor of SettingsLink, which breaks this PR on macOS 14 and above and could require a full rewrite to avoid more overhead/bugs; in all cases, this whole project is a demonstrable failure on Riot's end to implement a simple NSTrackingArea in their main window with a mouseExited() callback. League players shouldn't have to use a hacky workaround that adds unnecessary overhead, but here we are.

**Comment by pldumn** [comment]
@relalis thank you for the release!

I've been looking into mouselock trying to understand what causes the polling rate issue. Apparently if you use a mouse with a polling rate > 250hz the cursor goes crazy in game.

Do you know what could be the cause?

**Comment by relalis** [comment]
> @relalis thank you for the release!
> 
> I've been looking into mouselock trying to understand what causes the polling rate issue. Apparently if you use a mouse with a polling rate > 250hz the cursor goes crazy in game.
> 
> Do you know what could be the cause?

I honestly couldn't say; I don't really know much Swift, I just really liked the project and thought I'd add a little to it. I'll try to replicate sometime and see if I can debug, but no promises.

**Comment by ghost** [comment]
> @relalis thank you for the release!
> 
> 
> 
> I've been looking into mouselock trying to understand what causes the polling rate issue. Apparently if you use a mouse with a polling rate > 250hz the cursor goes crazy in game.
> 
> 
> 
> Do you know what could be the cause?

Turn off software mouse in game settings.

**Comment by pldumn** [comment]
@relalis thank you!

@kejedi tried it but didn't work unfortunately. If mouselock is not running the mouse works normally, it only does that when it is running.

**Comment by mxrlkn** [comment]
as explained here https://github.com/mxrlkn/mouselock/issues/9#issuecomment-2276791019
I've decided that it's better that it'll not be a menubar app after all. I just think it's simpler without. And also this problem should not still be a thing.

Surely Riot will fix this soon (aware)

**Pull request closed without merging**
